/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MirrorRouteImport } from './routes/mirror'
import { Route as CityHallRouteImport } from './routes/city-hall'
import { Route as IndexRouteImport } from './routes/index'

const MirrorRoute = MirrorRouteImport.update({
  id: '/mirror',
  path: '/mirror',
  getParentRoute: () => rootRouteImport,
} as any)
const CityHallRoute = CityHallRouteImport.update({
  id: '/city-hall',
  path: '/city-hall',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/city-hall': typeof CityHallRoute
  '/mirror': typeof MirrorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/city-hall': typeof CityHallRoute
  '/mirror': typeof MirrorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/city-hall': typeof CityHallRoute
  '/mirror': typeof MirrorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/city-hall' | '/mirror'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/city-hall' | '/mirror'
  id: '__root__' | '/' | '/city-hall' | '/mirror'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CityHallRoute: typeof CityHallRoute
  MirrorRoute: typeof MirrorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mirror': {
      id: '/mirror'
      path: '/mirror'
      fullPath: '/mirror'
      preLoaderRoute: typeof MirrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city-hall': {
      id: '/city-hall'
      path: '/city-hall'
      fullPath: '/city-hall'
      preLoaderRoute: typeof CityHallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CityHallRoute: CityHallRoute,
  MirrorRoute: MirrorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
