/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CityHallRouteImport } from './routes/city-hall'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MirrorIndexRouteImport } from './routes/mirror.index'
import { Route as MirrorCaseIdRouteImport } from './routes/mirror.$caseId'

const CityHallRoute = CityHallRouteImport.update({
  id: '/city-hall',
  path: '/city-hall',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MirrorIndexRoute = MirrorIndexRouteImport.update({
  id: '/mirror/',
  path: '/mirror/',
  getParentRoute: () => rootRouteImport,
} as any)
const MirrorCaseIdRoute = MirrorCaseIdRouteImport.update({
  id: '/mirror/$caseId',
  path: '/mirror/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/city-hall': typeof CityHallRoute
  '/mirror/$caseId': typeof MirrorCaseIdRoute
  '/mirror/': typeof MirrorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/city-hall': typeof CityHallRoute
  '/mirror/$caseId': typeof MirrorCaseIdRoute
  '/mirror': typeof MirrorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/city-hall': typeof CityHallRoute
  '/mirror/$caseId': typeof MirrorCaseIdRoute
  '/mirror/': typeof MirrorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/city-hall' | '/mirror/$caseId' | '/mirror/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/city-hall' | '/mirror/$caseId' | '/mirror'
  id: '__root__' | '/' | '/city-hall' | '/mirror/$caseId' | '/mirror/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CityHallRoute: typeof CityHallRoute
  MirrorCaseIdRoute: typeof MirrorCaseIdRoute
  MirrorIndexRoute: typeof MirrorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/city-hall': {
      id: '/city-hall'
      path: '/city-hall'
      fullPath: '/city-hall'
      preLoaderRoute: typeof CityHallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mirror/': {
      id: '/mirror/'
      path: '/mirror'
      fullPath: '/mirror/'
      preLoaderRoute: typeof MirrorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mirror/$caseId': {
      id: '/mirror/$caseId'
      path: '/mirror/$caseId'
      fullPath: '/mirror/$caseId'
      preLoaderRoute: typeof MirrorCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CityHallRoute: CityHallRoute,
  MirrorCaseIdRoute: MirrorCaseIdRoute,
  MirrorIndexRoute: MirrorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
